title: Josh Breiger # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description Knowledgeable data analyst and data engineer who is currently a second-year master’s student in the Information Management program at the UW specializing in BI and data science. 
  <br><br>
  Second description Multiple years of experience collecting, analyzing, and presenting data. Striving to use excellent analytical and data organizational abilities to help companies and clients achieve their data driven outcomes. 
  <br><br>
  <a href="https://www.linkedin.com/in/joshbreiger/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
